<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Pokemon extends Model
{
    use Sushi;

    protected $rows = [
        [
            "id" => 1,
            "name" => "bulbasaur",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
            "base_experience" => 64,
            "height" => 7,
            "weight" => 69,
            "attack" => 49,
            "defense" => 49,
            "hp" => 45,
            "speed" => 45,
            "special_attack" => 65,
            "special_defense" => 65,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 2,
            "name" => "ivysaur",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
            "base_experience" => 142,
            "height" => 10,
            "weight" => 130,
            "attack" => 62,
            "defense" => 63,
            "hp" => 60,
            "speed" => 60,
            "special_attack" => 80,
            "special_defense" => 80,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 3,
            "name" => "venusaur",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
            "base_experience" => 263,
            "height" => 20,
            "weight" => 1000,
            "attack" => 82,
            "defense" => 83,
            "hp" => 80,
            "speed" => 80,
            "special_attack" => 100,
            "special_defense" => 100,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 4,
            "name" => "charmander",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
            "base_experience" => 62,
            "height" => 6,
            "weight" => 85,
            "attack" => 52,
            "defense" => 43,
            "hp" => 39,
            "speed" => 65,
            "special_attack" => 60,
            "special_defense" => 50,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 5,
            "name" => "charmeleon",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
            "base_experience" => 142,
            "height" => 11,
            "weight" => 190,
            "attack" => 64,
            "defense" => 58,
            "hp" => 58,
            "speed" => 80,
            "special_attack" => 80,
            "special_defense" => 65,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 6,
            "name" => "charizard",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
            "base_experience" => 267,
            "height" => 17,
            "weight" => 905,
            "attack" => 84,
            "defense" => 78,
            "hp" => 78,
            "speed" => 100,
            "special_attack" => 109,
            "special_defense" => 85,
            "primary_type" => "fire",
            "secondary_type" => "flying"
        ],
        [
            "id" => 7,
            "name" => "squirtle",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
            "base_experience" => 63,
            "height" => 5,
            "weight" => 90,
            "attack" => 48,
            "defense" => 65,
            "hp" => 44,
            "speed" => 43,
            "special_attack" => 50,
            "special_defense" => 64,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 8,
            "name" => "wartortle",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
            "base_experience" => 142,
            "height" => 10,
            "weight" => 225,
            "attack" => 63,
            "defense" => 80,
            "hp" => 59,
            "speed" => 58,
            "special_attack" => 65,
            "special_defense" => 80,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 9,
            "name" => "blastoise",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
            "base_experience" => 265,
            "height" => 16,
            "weight" => 855,
            "attack" => 83,
            "defense" => 100,
            "hp" => 79,
            "speed" => 78,
            "special_attack" => 85,
            "special_defense" => 105,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 10,
            "name" => "caterpie",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
            "base_experience" => 39,
            "height" => 3,
            "weight" => 29,
            "attack" => 30,
            "defense" => 35,
            "hp" => 45,
            "speed" => 45,
            "special_attack" => 20,
            "special_defense" => 20,
            "primary_type" => "bug",
            "secondary_type" => null
        ],
        [
            "id" => 11,
            "name" => "metapod",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
            "base_experience" => 72,
            "height" => 7,
            "weight" => 99,
            "attack" => 20,
            "defense" => 55,
            "hp" => 50,
            "speed" => 30,
            "special_attack" => 25,
            "special_defense" => 25,
            "primary_type" => "bug",
            "secondary_type" => null
        ],
        [
            "id" => 12,
            "name" => "butterfree",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
            "base_experience" => 198,
            "height" => 11,
            "weight" => 320,
            "attack" => 45,
            "defense" => 50,
            "hp" => 60,
            "speed" => 70,
            "special_attack" => 90,
            "special_defense" => 80,
            "primary_type" => "bug",
            "secondary_type" => "flying"
        ],
        [
            "id" => 13,
            "name" => "weedle",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
            "base_experience" => 39,
            "height" => 3,
            "weight" => 32,
            "attack" => 35,
            "defense" => 30,
            "hp" => 40,
            "speed" => 50,
            "special_attack" => 20,
            "special_defense" => 20,
            "primary_type" => "bug",
            "secondary_type" => "poison"
        ],
        [
            "id" => 14,
            "name" => "kakuna",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
            "base_experience" => 72,
            "height" => 6,
            "weight" => 100,
            "attack" => 25,
            "defense" => 50,
            "hp" => 45,
            "speed" => 35,
            "special_attack" => 25,
            "special_defense" => 25,
            "primary_type" => "bug",
            "secondary_type" => "poison"
        ],
        [
            "id" => 15,
            "name" => "beedrill",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
            "base_experience" => 178,
            "height" => 10,
            "weight" => 295,
            "attack" => 90,
            "defense" => 40,
            "hp" => 65,
            "speed" => 75,
            "special_attack" => 45,
            "special_defense" => 80,
            "primary_type" => "bug",
            "secondary_type" => "poison"
        ],
        [
            "id" => 16,
            "name" => "pidgey",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
            "base_experience" => 50,
            "height" => 3,
            "weight" => 18,
            "attack" => 45,
            "defense" => 40,
            "hp" => 40,
            "speed" => 56,
            "special_attack" => 35,
            "special_defense" => 35,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 17,
            "name" => "pidgeotto",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
            "base_experience" => 122,
            "height" => 11,
            "weight" => 300,
            "attack" => 60,
            "defense" => 55,
            "hp" => 63,
            "speed" => 71,
            "special_attack" => 50,
            "special_defense" => 50,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 18,
            "name" => "pidgeot",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
            "base_experience" => 216,
            "height" => 15,
            "weight" => 395,
            "attack" => 80,
            "defense" => 75,
            "hp" => 83,
            "speed" => 101,
            "special_attack" => 70,
            "special_defense" => 70,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 19,
            "name" => "rattata",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
            "base_experience" => 51,
            "height" => 3,
            "weight" => 35,
            "attack" => 56,
            "defense" => 35,
            "hp" => 30,
            "speed" => 72,
            "special_attack" => 25,
            "special_defense" => 35,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 20,
            "name" => "raticate",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
            "base_experience" => 145,
            "height" => 7,
            "weight" => 185,
            "attack" => 81,
            "defense" => 60,
            "hp" => 55,
            "speed" => 97,
            "special_attack" => 50,
            "special_defense" => 70,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 21,
            "name" => "spearow",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
            "base_experience" => 52,
            "height" => 3,
            "weight" => 20,
            "attack" => 60,
            "defense" => 30,
            "hp" => 40,
            "speed" => 70,
            "special_attack" => 31,
            "special_defense" => 31,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 22,
            "name" => "fearow",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
            "base_experience" => 155,
            "height" => 12,
            "weight" => 380,
            "attack" => 90,
            "defense" => 65,
            "hp" => 65,
            "speed" => 100,
            "special_attack" => 61,
            "special_defense" => 61,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 23,
            "name" => "ekans",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
            "base_experience" => 58,
            "height" => 20,
            "weight" => 69,
            "attack" => 60,
            "defense" => 44,
            "hp" => 35,
            "speed" => 55,
            "special_attack" => 40,
            "special_defense" => 54,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 24,
            "name" => "arbok",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
            "base_experience" => 157,
            "height" => 35,
            "weight" => 650,
            "attack" => 95,
            "defense" => 69,
            "hp" => 60,
            "speed" => 80,
            "special_attack" => 65,
            "special_defense" => 79,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 25,
            "name" => "pikachu",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
            "base_experience" => 112,
            "height" => 4,
            "weight" => 60,
            "attack" => 55,
            "defense" => 40,
            "hp" => 35,
            "speed" => 90,
            "special_attack" => 50,
            "special_defense" => 50,
            "primary_type" => "electric",
            "secondary_type" => null
        ],
        [
            "id" => 26,
            "name" => "raichu",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
            "base_experience" => 243,
            "height" => 8,
            "weight" => 300,
            "attack" => 90,
            "defense" => 55,
            "hp" => 60,
            "speed" => 110,
            "special_attack" => 90,
            "special_defense" => 80,
            "primary_type" => "electric",
            "secondary_type" => null
        ],
        [
            "id" => 27,
            "name" => "sandshrew",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
            "base_experience" => 60,
            "height" => 6,
            "weight" => 120,
            "attack" => 75,
            "defense" => 85,
            "hp" => 50,
            "speed" => 40,
            "special_attack" => 20,
            "special_defense" => 30,
            "primary_type" => "ground",
            "secondary_type" => null
        ],
        [
            "id" => 28,
            "name" => "sandslash",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png",
            "base_experience" => 158,
            "height" => 10,
            "weight" => 295,
            "attack" => 100,
            "defense" => 110,
            "hp" => 75,
            "speed" => 65,
            "special_attack" => 45,
            "special_defense" => 55,
            "primary_type" => "ground",
            "secondary_type" => null
        ],
        [
            "id" => 29,
            "name" => "nidoran-f",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png",
            "base_experience" => 55,
            "height" => 4,
            "weight" => 70,
            "attack" => 47,
            "defense" => 52,
            "hp" => 55,
            "speed" => 41,
            "special_attack" => 40,
            "special_defense" => 40,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 30,
            "name" => "nidorina",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png",
            "base_experience" => 128,
            "height" => 8,
            "weight" => 200,
            "attack" => 62,
            "defense" => 67,
            "hp" => 70,
            "speed" => 56,
            "special_attack" => 55,
            "special_defense" => 55,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 31,
            "name" => "nidoqueen",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png",
            "base_experience" => 253,
            "height" => 13,
            "weight" => 600,
            "attack" => 92,
            "defense" => 87,
            "hp" => 90,
            "speed" => 76,
            "special_attack" => 75,
            "special_defense" => 85,
            "primary_type" => "poison",
            "secondary_type" => "ground"
        ],
        [
            "id" => 32,
            "name" => "nidoran-m",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png",
            "base_experience" => 55,
            "height" => 5,
            "weight" => 90,
            "attack" => 57,
            "defense" => 40,
            "hp" => 46,
            "speed" => 50,
            "special_attack" => 40,
            "special_defense" => 40,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 33,
            "name" => "nidorino",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png",
            "base_experience" => 128,
            "height" => 9,
            "weight" => 195,
            "attack" => 72,
            "defense" => 57,
            "hp" => 61,
            "speed" => 65,
            "special_attack" => 55,
            "special_defense" => 55,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 34,
            "name" => "nidoking",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png",
            "base_experience" => 253,
            "height" => 14,
            "weight" => 620,
            "attack" => 102,
            "defense" => 77,
            "hp" => 81,
            "speed" => 85,
            "special_attack" => 85,
            "special_defense" => 75,
            "primary_type" => "poison",
            "secondary_type" => "ground"
        ],
        [
            "id" => 35,
            "name" => "clefairy",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png",
            "base_experience" => 113,
            "height" => 6,
            "weight" => 75,
            "attack" => 45,
            "defense" => 48,
            "hp" => 70,
            "speed" => 35,
            "special_attack" => 60,
            "special_defense" => 65,
            "primary_type" => "fairy",
            "secondary_type" => null
        ],
        [
            "id" => 36,
            "name" => "clefable",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png",
            "base_experience" => 242,
            "height" => 13,
            "weight" => 400,
            "attack" => 70,
            "defense" => 73,
            "hp" => 95,
            "speed" => 60,
            "special_attack" => 95,
            "special_defense" => 90,
            "primary_type" => "fairy",
            "secondary_type" => null
        ],
        [
            "id" => 37,
            "name" => "vulpix",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png",
            "base_experience" => 60,
            "height" => 6,
            "weight" => 99,
            "attack" => 41,
            "defense" => 40,
            "hp" => 38,
            "speed" => 65,
            "special_attack" => 50,
            "special_defense" => 65,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 38,
            "name" => "ninetales",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png",
            "base_experience" => 177,
            "height" => 11,
            "weight" => 199,
            "attack" => 76,
            "defense" => 75,
            "hp" => 73,
            "speed" => 100,
            "special_attack" => 81,
            "special_defense" => 100,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 39,
            "name" => "jigglypuff",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
            "base_experience" => 95,
            "height" => 5,
            "weight" => 55,
            "attack" => 45,
            "defense" => 20,
            "hp" => 115,
            "speed" => 20,
            "special_attack" => 45,
            "special_defense" => 25,
            "primary_type" => "normal",
            "secondary_type" => "fairy"
        ],
        [
            "id" => 40,
            "name" => "wigglytuff",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png",
            "base_experience" => 218,
            "height" => 10,
            "weight" => 120,
            "attack" => 70,
            "defense" => 45,
            "hp" => 140,
            "speed" => 45,
            "special_attack" => 85,
            "special_defense" => 50,
            "primary_type" => "normal",
            "secondary_type" => "fairy"
        ],
        [
            "id" => 41,
            "name" => "zubat",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png",
            "base_experience" => 49,
            "height" => 8,
            "weight" => 75,
            "attack" => 45,
            "defense" => 35,
            "hp" => 40,
            "speed" => 55,
            "special_attack" => 30,
            "special_defense" => 40,
            "primary_type" => "poison",
            "secondary_type" => "flying"
        ],
        [
            "id" => 42,
            "name" => "golbat",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png",
            "base_experience" => 159,
            "height" => 16,
            "weight" => 550,
            "attack" => 80,
            "defense" => 70,
            "hp" => 75,
            "speed" => 90,
            "special_attack" => 65,
            "special_defense" => 75,
            "primary_type" => "poison",
            "secondary_type" => "flying"
        ],
        [
            "id" => 43,
            "name" => "oddish",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png",
            "base_experience" => 64,
            "height" => 5,
            "weight" => 54,
            "attack" => 50,
            "defense" => 55,
            "hp" => 45,
            "speed" => 30,
            "special_attack" => 75,
            "special_defense" => 65,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 44,
            "name" => "gloom",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png",
            "base_experience" => 138,
            "height" => 8,
            "weight" => 86,
            "attack" => 65,
            "defense" => 70,
            "hp" => 60,
            "speed" => 40,
            "special_attack" => 85,
            "special_defense" => 75,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 45,
            "name" => "vileplume",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png",
            "base_experience" => 245,
            "height" => 12,
            "weight" => 186,
            "attack" => 80,
            "defense" => 85,
            "hp" => 75,
            "speed" => 50,
            "special_attack" => 110,
            "special_defense" => 90,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 46,
            "name" => "paras",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png",
            "base_experience" => 57,
            "height" => 3,
            "weight" => 54,
            "attack" => 70,
            "defense" => 55,
            "hp" => 35,
            "speed" => 25,
            "special_attack" => 45,
            "special_defense" => 55,
            "primary_type" => "bug",
            "secondary_type" => "grass"
        ],
        [
            "id" => 47,
            "name" => "parasect",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png",
            "base_experience" => 142,
            "height" => 10,
            "weight" => 295,
            "attack" => 95,
            "defense" => 80,
            "hp" => 60,
            "speed" => 30,
            "special_attack" => 60,
            "special_defense" => 80,
            "primary_type" => "bug",
            "secondary_type" => "grass"
        ],
        [
            "id" => 48,
            "name" => "venonat",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png",
            "base_experience" => 61,
            "height" => 10,
            "weight" => 300,
            "attack" => 55,
            "defense" => 50,
            "hp" => 60,
            "speed" => 45,
            "special_attack" => 40,
            "special_defense" => 55,
            "primary_type" => "bug",
            "secondary_type" => "poison"
        ],
        [
            "id" => 49,
            "name" => "venomoth",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png",
            "base_experience" => 158,
            "height" => 15,
            "weight" => 125,
            "attack" => 65,
            "defense" => 60,
            "hp" => 70,
            "speed" => 90,
            "special_attack" => 90,
            "special_defense" => 75,
            "primary_type" => "bug",
            "secondary_type" => "poison"
        ],
        [
            "id" => 50,
            "name" => "diglett",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png",
            "base_experience" => 53,
            "height" => 2,
            "weight" => 8,
            "attack" => 55,
            "defense" => 25,
            "hp" => 10,
            "speed" => 95,
            "special_attack" => 35,
            "special_defense" => 45,
            "primary_type" => "ground",
            "secondary_type" => null
        ],
        [
            "id" => 51,
            "name" => "dugtrio",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png",
            "base_experience" => 149,
            "height" => 7,
            "weight" => 333,
            "attack" => 100,
            "defense" => 50,
            "hp" => 35,
            "speed" => 120,
            "special_attack" => 50,
            "special_defense" => 70,
            "primary_type" => "ground",
            "secondary_type" => null
        ],
        [
            "id" => 52,
            "name" => "meowth",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png",
            "base_experience" => 58,
            "height" => 4,
            "weight" => 42,
            "attack" => 45,
            "defense" => 35,
            "hp" => 40,
            "speed" => 90,
            "special_attack" => 40,
            "special_defense" => 40,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 53,
            "name" => "persian",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png",
            "base_experience" => 154,
            "height" => 10,
            "weight" => 320,
            "attack" => 70,
            "defense" => 60,
            "hp" => 65,
            "speed" => 115,
            "special_attack" => 65,
            "special_defense" => 65,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 54,
            "name" => "psyduck",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png",
            "base_experience" => 64,
            "height" => 8,
            "weight" => 196,
            "attack" => 52,
            "defense" => 48,
            "hp" => 50,
            "speed" => 55,
            "special_attack" => 65,
            "special_defense" => 50,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 55,
            "name" => "golduck",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png",
            "base_experience" => 175,
            "height" => 17,
            "weight" => 766,
            "attack" => 82,
            "defense" => 78,
            "hp" => 80,
            "speed" => 85,
            "special_attack" => 95,
            "special_defense" => 80,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 56,
            "name" => "mankey",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png",
            "base_experience" => 61,
            "height" => 5,
            "weight" => 280,
            "attack" => 80,
            "defense" => 35,
            "hp" => 40,
            "speed" => 70,
            "special_attack" => 35,
            "special_defense" => 45,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 57,
            "name" => "primeape",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png",
            "base_experience" => 159,
            "height" => 10,
            "weight" => 320,
            "attack" => 105,
            "defense" => 60,
            "hp" => 65,
            "speed" => 95,
            "special_attack" => 60,
            "special_defense" => 70,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 58,
            "name" => "growlithe",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png",
            "base_experience" => 70,
            "height" => 7,
            "weight" => 190,
            "attack" => 70,
            "defense" => 45,
            "hp" => 55,
            "speed" => 60,
            "special_attack" => 70,
            "special_defense" => 50,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 59,
            "name" => "arcanine",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png",
            "base_experience" => 194,
            "height" => 19,
            "weight" => 1550,
            "attack" => 110,
            "defense" => 80,
            "hp" => 90,
            "speed" => 95,
            "special_attack" => 100,
            "special_defense" => 80,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 60,
            "name" => "poliwag",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png",
            "base_experience" => 60,
            "height" => 6,
            "weight" => 124,
            "attack" => 50,
            "defense" => 40,
            "hp" => 40,
            "speed" => 90,
            "special_attack" => 40,
            "special_defense" => 40,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 61,
            "name" => "poliwhirl",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png",
            "base_experience" => 135,
            "height" => 10,
            "weight" => 200,
            "attack" => 65,
            "defense" => 65,
            "hp" => 65,
            "speed" => 90,
            "special_attack" => 50,
            "special_defense" => 50,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 62,
            "name" => "poliwrath",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png",
            "base_experience" => 255,
            "height" => 13,
            "weight" => 540,
            "attack" => 95,
            "defense" => 95,
            "hp" => 90,
            "speed" => 70,
            "special_attack" => 70,
            "special_defense" => 90,
            "primary_type" => "water",
            "secondary_type" => "fighting"
        ],
        [
            "id" => 63,
            "name" => "abra",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
            "base_experience" => 62,
            "height" => 9,
            "weight" => 195,
            "attack" => 20,
            "defense" => 15,
            "hp" => 25,
            "speed" => 90,
            "special_attack" => 105,
            "special_defense" => 55,
            "primary_type" => "psychic",
            "secondary_type" => null
        ],
        [
            "id" => 64,
            "name" => "kadabra",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png",
            "base_experience" => 140,
            "height" => 13,
            "weight" => 565,
            "attack" => 35,
            "defense" => 30,
            "hp" => 40,
            "speed" => 105,
            "special_attack" => 120,
            "special_defense" => 70,
            "primary_type" => "psychic",
            "secondary_type" => null
        ],
        [
            "id" => 65,
            "name" => "alakazam",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png",
            "base_experience" => 250,
            "height" => 15,
            "weight" => 480,
            "attack" => 50,
            "defense" => 45,
            "hp" => 55,
            "speed" => 120,
            "special_attack" => 135,
            "special_defense" => 95,
            "primary_type" => "psychic",
            "secondary_type" => null
        ],
        [
            "id" => 66,
            "name" => "machop",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
            "base_experience" => 61,
            "height" => 8,
            "weight" => 195,
            "attack" => 80,
            "defense" => 50,
            "hp" => 70,
            "speed" => 35,
            "special_attack" => 35,
            "special_defense" => 35,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 67,
            "name" => "machoke",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png",
            "base_experience" => 142,
            "height" => 15,
            "weight" => 705,
            "attack" => 100,
            "defense" => 70,
            "hp" => 80,
            "speed" => 45,
            "special_attack" => 50,
            "special_defense" => 60,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 68,
            "name" => "machamp",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png",
            "base_experience" => 253,
            "height" => 16,
            "weight" => 1300,
            "attack" => 130,
            "defense" => 80,
            "hp" => 90,
            "speed" => 55,
            "special_attack" => 65,
            "special_defense" => 85,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 69,
            "name" => "bellsprout",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png",
            "base_experience" => 60,
            "height" => 7,
            "weight" => 40,
            "attack" => 75,
            "defense" => 35,
            "hp" => 50,
            "speed" => 40,
            "special_attack" => 70,
            "special_defense" => 30,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 70,
            "name" => "weepinbell",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png",
            "base_experience" => 137,
            "height" => 10,
            "weight" => 64,
            "attack" => 90,
            "defense" => 50,
            "hp" => 65,
            "speed" => 55,
            "special_attack" => 85,
            "special_defense" => 45,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 71,
            "name" => "victreebel",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png",
            "base_experience" => 221,
            "height" => 17,
            "weight" => 155,
            "attack" => 105,
            "defense" => 65,
            "hp" => 80,
            "speed" => 70,
            "special_attack" => 100,
            "special_defense" => 70,
            "primary_type" => "grass",
            "secondary_type" => "poison"
        ],
        [
            "id" => 72,
            "name" => "tentacool",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png",
            "base_experience" => 67,
            "height" => 9,
            "weight" => 455,
            "attack" => 40,
            "defense" => 35,
            "hp" => 40,
            "speed" => 70,
            "special_attack" => 50,
            "special_defense" => 100,
            "primary_type" => "water",
            "secondary_type" => "poison"
        ],
        [
            "id" => 73,
            "name" => "tentacruel",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png",
            "base_experience" => 180,
            "height" => 16,
            "weight" => 550,
            "attack" => 70,
            "defense" => 65,
            "hp" => 80,
            "speed" => 100,
            "special_attack" => 80,
            "special_defense" => 120,
            "primary_type" => "water",
            "secondary_type" => "poison"
        ],
        [
            "id" => 74,
            "name" => "geodude",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
            "base_experience" => 60,
            "height" => 4,
            "weight" => 200,
            "attack" => 80,
            "defense" => 100,
            "hp" => 40,
            "speed" => 20,
            "special_attack" => 30,
            "special_defense" => 30,
            "primary_type" => "rock",
            "secondary_type" => "ground"
        ],
        [
            "id" => 75,
            "name" => "graveler",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png",
            "base_experience" => 137,
            "height" => 10,
            "weight" => 1050,
            "attack" => 95,
            "defense" => 115,
            "hp" => 55,
            "speed" => 35,
            "special_attack" => 45,
            "special_defense" => 45,
            "primary_type" => "rock",
            "secondary_type" => "ground"
        ],
        [
            "id" => 76,
            "name" => "golem",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png",
            "base_experience" => 223,
            "height" => 14,
            "weight" => 3000,
            "attack" => 120,
            "defense" => 130,
            "hp" => 80,
            "speed" => 45,
            "special_attack" => 55,
            "special_defense" => 65,
            "primary_type" => "rock",
            "secondary_type" => "ground"
        ],
        [
            "id" => 77,
            "name" => "ponyta",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png",
            "base_experience" => 82,
            "height" => 10,
            "weight" => 300,
            "attack" => 85,
            "defense" => 55,
            "hp" => 50,
            "speed" => 90,
            "special_attack" => 65,
            "special_defense" => 65,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 78,
            "name" => "rapidash",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png",
            "base_experience" => 175,
            "height" => 17,
            "weight" => 950,
            "attack" => 100,
            "defense" => 70,
            "hp" => 65,
            "speed" => 105,
            "special_attack" => 80,
            "special_defense" => 80,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 79,
            "name" => "slowpoke",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png",
            "base_experience" => 63,
            "height" => 12,
            "weight" => 360,
            "attack" => 65,
            "defense" => 65,
            "hp" => 90,
            "speed" => 15,
            "special_attack" => 40,
            "special_defense" => 40,
            "primary_type" => "water",
            "secondary_type" => "psychic"
        ],
        [
            "id" => 80,
            "name" => "slowbro",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png",
            "base_experience" => 172,
            "height" => 16,
            "weight" => 785,
            "attack" => 75,
            "defense" => 110,
            "hp" => 95,
            "speed" => 30,
            "special_attack" => 100,
            "special_defense" => 80,
            "primary_type" => "water",
            "secondary_type" => "psychic"
        ],
        [
            "id" => 81,
            "name" => "magnemite",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png",
            "base_experience" => 65,
            "height" => 3,
            "weight" => 60,
            "attack" => 35,
            "defense" => 70,
            "hp" => 25,
            "speed" => 45,
            "special_attack" => 95,
            "special_defense" => 55,
            "primary_type" => "electric",
            "secondary_type" => "steel"
        ],
        [
            "id" => 82,
            "name" => "magneton",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png",
            "base_experience" => 163,
            "height" => 10,
            "weight" => 600,
            "attack" => 60,
            "defense" => 95,
            "hp" => 50,
            "speed" => 70,
            "special_attack" => 120,
            "special_defense" => 70,
            "primary_type" => "electric",
            "secondary_type" => "steel"
        ],
        [
            "id" => 83,
            "name" => "farfetchd",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png",
            "base_experience" => 132,
            "height" => 8,
            "weight" => 150,
            "attack" => 90,
            "defense" => 55,
            "hp" => 52,
            "speed" => 60,
            "special_attack" => 58,
            "special_defense" => 62,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 84,
            "name" => "doduo",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png",
            "base_experience" => 62,
            "height" => 14,
            "weight" => 392,
            "attack" => 85,
            "defense" => 45,
            "hp" => 35,
            "speed" => 75,
            "special_attack" => 35,
            "special_defense" => 35,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 85,
            "name" => "dodrio",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png",
            "base_experience" => 165,
            "height" => 18,
            "weight" => 852,
            "attack" => 110,
            "defense" => 70,
            "hp" => 60,
            "speed" => 110,
            "special_attack" => 60,
            "special_defense" => 60,
            "primary_type" => "normal",
            "secondary_type" => "flying"
        ],
        [
            "id" => 86,
            "name" => "seel",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png",
            "base_experience" => 65,
            "height" => 11,
            "weight" => 900,
            "attack" => 45,
            "defense" => 55,
            "hp" => 65,
            "speed" => 45,
            "special_attack" => 45,
            "special_defense" => 70,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 87,
            "name" => "dewgong",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png",
            "base_experience" => 166,
            "height" => 17,
            "weight" => 1200,
            "attack" => 70,
            "defense" => 80,
            "hp" => 90,
            "speed" => 70,
            "special_attack" => 70,
            "special_defense" => 95,
            "primary_type" => "water",
            "secondary_type" => "ice"
        ],
        [
            "id" => 88,
            "name" => "grimer",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png",
            "base_experience" => 65,
            "height" => 9,
            "weight" => 300,
            "attack" => 80,
            "defense" => 50,
            "hp" => 80,
            "speed" => 25,
            "special_attack" => 40,
            "special_defense" => 50,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 89,
            "name" => "muk",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png",
            "base_experience" => 175,
            "height" => 12,
            "weight" => 300,
            "attack" => 105,
            "defense" => 75,
            "hp" => 105,
            "speed" => 50,
            "special_attack" => 65,
            "special_defense" => 100,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 90,
            "name" => "shellder",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png",
            "base_experience" => 61,
            "height" => 3,
            "weight" => 40,
            "attack" => 65,
            "defense" => 100,
            "hp" => 30,
            "speed" => 40,
            "special_attack" => 45,
            "special_defense" => 25,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 91,
            "name" => "cloyster",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png",
            "base_experience" => 184,
            "height" => 15,
            "weight" => 1325,
            "attack" => 95,
            "defense" => 180,
            "hp" => 50,
            "speed" => 70,
            "special_attack" => 85,
            "special_defense" => 45,
            "primary_type" => "water",
            "secondary_type" => "ice"
        ],
        [
            "id" => 92,
            "name" => "gastly",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
            "base_experience" => 62,
            "height" => 13,
            "weight" => 1,
            "attack" => 35,
            "defense" => 30,
            "hp" => 30,
            "speed" => 80,
            "special_attack" => 100,
            "special_defense" => 35,
            "primary_type" => "ghost",
            "secondary_type" => "poison"
        ],
        [
            "id" => 93,
            "name" => "haunter",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png",
            "base_experience" => 142,
            "height" => 16,
            "weight" => 1,
            "attack" => 50,
            "defense" => 45,
            "hp" => 45,
            "speed" => 95,
            "special_attack" => 115,
            "special_defense" => 55,
            "primary_type" => "ghost",
            "secondary_type" => "poison"
        ],
        [
            "id" => 94,
            "name" => "gengar",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
            "base_experience" => 250,
            "height" => 15,
            "weight" => 405,
            "attack" => 65,
            "defense" => 60,
            "hp" => 60,
            "speed" => 110,
            "special_attack" => 130,
            "special_defense" => 75,
            "primary_type" => "ghost",
            "secondary_type" => "poison"
        ],
        [
            "id" => 95,
            "name" => "onix",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png",
            "base_experience" => 77,
            "height" => 88,
            "weight" => 2100,
            "attack" => 45,
            "defense" => 160,
            "hp" => 35,
            "speed" => 70,
            "special_attack" => 30,
            "special_defense" => 45,
            "primary_type" => "rock",
            "secondary_type" => "ground"
        ],
        [
            "id" => 96,
            "name" => "drowzee",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png",
            "base_experience" => 66,
            "height" => 10,
            "weight" => 324,
            "attack" => 48,
            "defense" => 45,
            "hp" => 60,
            "speed" => 42,
            "special_attack" => 43,
            "special_defense" => 90,
            "primary_type" => "psychic",
            "secondary_type" => null
        ],
        [
            "id" => 97,
            "name" => "hypno",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png",
            "base_experience" => 169,
            "height" => 16,
            "weight" => 756,
            "attack" => 73,
            "defense" => 70,
            "hp" => 85,
            "speed" => 67,
            "special_attack" => 73,
            "special_defense" => 115,
            "primary_type" => "psychic",
            "secondary_type" => null
        ],
        [
            "id" => 98,
            "name" => "krabby",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png",
            "base_experience" => 65,
            "height" => 4,
            "weight" => 65,
            "attack" => 105,
            "defense" => 90,
            "hp" => 30,
            "speed" => 50,
            "special_attack" => 25,
            "special_defense" => 25,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 99,
            "name" => "kingler",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png",
            "base_experience" => 166,
            "height" => 13,
            "weight" => 600,
            "attack" => 130,
            "defense" => 115,
            "hp" => 55,
            "speed" => 75,
            "special_attack" => 50,
            "special_defense" => 50,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 100,
            "name" => "voltorb",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png",
            "base_experience" => 66,
            "height" => 5,
            "weight" => 104,
            "attack" => 30,
            "defense" => 50,
            "hp" => 40,
            "speed" => 100,
            "special_attack" => 55,
            "special_defense" => 55,
            "primary_type" => "electric",
            "secondary_type" => null
        ],
        [
            "id" => 101,
            "name" => "electrode",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png",
            "base_experience" => 172,
            "height" => 12,
            "weight" => 666,
            "attack" => 50,
            "defense" => 70,
            "hp" => 60,
            "speed" => 150,
            "special_attack" => 80,
            "special_defense" => 80,
            "primary_type" => "electric",
            "secondary_type" => null
        ],
        [
            "id" => 102,
            "name" => "exeggcute",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png",
            "base_experience" => 65,
            "height" => 4,
            "weight" => 25,
            "attack" => 40,
            "defense" => 80,
            "hp" => 60,
            "speed" => 40,
            "special_attack" => 60,
            "special_defense" => 45,
            "primary_type" => "grass",
            "secondary_type" => "psychic"
        ],
        [
            "id" => 103,
            "name" => "exeggutor",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png",
            "base_experience" => 186,
            "height" => 20,
            "weight" => 1200,
            "attack" => 95,
            "defense" => 85,
            "hp" => 95,
            "speed" => 55,
            "special_attack" => 125,
            "special_defense" => 75,
            "primary_type" => "grass",
            "secondary_type" => "psychic"
        ],
        [
            "id" => 104,
            "name" => "cubone",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png",
            "base_experience" => 64,
            "height" => 4,
            "weight" => 65,
            "attack" => 50,
            "defense" => 95,
            "hp" => 50,
            "speed" => 35,
            "special_attack" => 40,
            "special_defense" => 50,
            "primary_type" => "ground",
            "secondary_type" => null
        ],
        [
            "id" => 105,
            "name" => "marowak",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png",
            "base_experience" => 149,
            "height" => 10,
            "weight" => 450,
            "attack" => 80,
            "defense" => 110,
            "hp" => 60,
            "speed" => 45,
            "special_attack" => 50,
            "special_defense" => 80,
            "primary_type" => "ground",
            "secondary_type" => null
        ],
        [
            "id" => 106,
            "name" => "hitmonlee",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png",
            "base_experience" => 159,
            "height" => 15,
            "weight" => 498,
            "attack" => 120,
            "defense" => 53,
            "hp" => 50,
            "speed" => 87,
            "special_attack" => 35,
            "special_defense" => 110,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 107,
            "name" => "hitmonchan",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png",
            "base_experience" => 159,
            "height" => 14,
            "weight" => 502,
            "attack" => 105,
            "defense" => 79,
            "hp" => 50,
            "speed" => 76,
            "special_attack" => 35,
            "special_defense" => 110,
            "primary_type" => "fighting",
            "secondary_type" => null
        ],
        [
            "id" => 108,
            "name" => "lickitung",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png",
            "base_experience" => 77,
            "height" => 12,
            "weight" => 655,
            "attack" => 55,
            "defense" => 75,
            "hp" => 90,
            "speed" => 30,
            "special_attack" => 60,
            "special_defense" => 75,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 109,
            "name" => "koffing",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png",
            "base_experience" => 68,
            "height" => 6,
            "weight" => 10,
            "attack" => 65,
            "defense" => 95,
            "hp" => 40,
            "speed" => 35,
            "special_attack" => 60,
            "special_defense" => 45,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 110,
            "name" => "weezing",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png",
            "base_experience" => 172,
            "height" => 12,
            "weight" => 95,
            "attack" => 90,
            "defense" => 120,
            "hp" => 65,
            "speed" => 60,
            "special_attack" => 85,
            "special_defense" => 70,
            "primary_type" => "poison",
            "secondary_type" => null
        ],
        [
            "id" => 111,
            "name" => "rhyhorn",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png",
            "base_experience" => 69,
            "height" => 10,
            "weight" => 1150,
            "attack" => 85,
            "defense" => 95,
            "hp" => 80,
            "speed" => 25,
            "special_attack" => 30,
            "special_defense" => 30,
            "primary_type" => "ground",
            "secondary_type" => "rock"
        ],
        [
            "id" => 112,
            "name" => "rhydon",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png",
            "base_experience" => 170,
            "height" => 19,
            "weight" => 1200,
            "attack" => 130,
            "defense" => 120,
            "hp" => 105,
            "speed" => 40,
            "special_attack" => 45,
            "special_defense" => 45,
            "primary_type" => "ground",
            "secondary_type" => "rock"
        ],
        [
            "id" => 113,
            "name" => "chansey",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png",
            "base_experience" => 395,
            "height" => 11,
            "weight" => 346,
            "attack" => 5,
            "defense" => 5,
            "hp" => 250,
            "speed" => 50,
            "special_attack" => 35,
            "special_defense" => 105,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 114,
            "name" => "tangela",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png",
            "base_experience" => 87,
            "height" => 10,
            "weight" => 350,
            "attack" => 55,
            "defense" => 115,
            "hp" => 65,
            "speed" => 60,
            "special_attack" => 100,
            "special_defense" => 40,
            "primary_type" => "grass",
            "secondary_type" => null
        ],
        [
            "id" => 115,
            "name" => "kangaskhan",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png",
            "base_experience" => 172,
            "height" => 22,
            "weight" => 800,
            "attack" => 95,
            "defense" => 80,
            "hp" => 105,
            "speed" => 90,
            "special_attack" => 40,
            "special_defense" => 80,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 116,
            "name" => "horsea",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png",
            "base_experience" => 59,
            "height" => 4,
            "weight" => 80,
            "attack" => 40,
            "defense" => 70,
            "hp" => 30,
            "speed" => 60,
            "special_attack" => 70,
            "special_defense" => 25,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 117,
            "name" => "seadra",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png",
            "base_experience" => 154,
            "height" => 12,
            "weight" => 250,
            "attack" => 65,
            "defense" => 95,
            "hp" => 55,
            "speed" => 85,
            "special_attack" => 95,
            "special_defense" => 45,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 118,
            "name" => "goldeen",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png",
            "base_experience" => 64,
            "height" => 6,
            "weight" => 150,
            "attack" => 67,
            "defense" => 60,
            "hp" => 45,
            "speed" => 63,
            "special_attack" => 35,
            "special_defense" => 50,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 119,
            "name" => "seaking",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png",
            "base_experience" => 158,
            "height" => 13,
            "weight" => 390,
            "attack" => 92,
            "defense" => 65,
            "hp" => 80,
            "speed" => 68,
            "special_attack" => 65,
            "special_defense" => 80,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 120,
            "name" => "staryu",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png",
            "base_experience" => 68,
            "height" => 8,
            "weight" => 345,
            "attack" => 45,
            "defense" => 55,
            "hp" => 30,
            "speed" => 85,
            "special_attack" => 70,
            "special_defense" => 55,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 121,
            "name" => "starmie",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png",
            "base_experience" => 182,
            "height" => 11,
            "weight" => 800,
            "attack" => 75,
            "defense" => 85,
            "hp" => 60,
            "speed" => 115,
            "special_attack" => 100,
            "special_defense" => 85,
            "primary_type" => "water",
            "secondary_type" => "psychic"
        ],
        [
            "id" => 122,
            "name" => "mr-mime",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png",
            "base_experience" => 161,
            "height" => 13,
            "weight" => 545,
            "attack" => 45,
            "defense" => 65,
            "hp" => 40,
            "speed" => 90,
            "special_attack" => 100,
            "special_defense" => 120,
            "primary_type" => "psychic",
            "secondary_type" => "fairy"
        ],
        [
            "id" => 123,
            "name" => "scyther",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png",
            "base_experience" => 100,
            "height" => 15,
            "weight" => 560,
            "attack" => 110,
            "defense" => 80,
            "hp" => 70,
            "speed" => 105,
            "special_attack" => 55,
            "special_defense" => 80,
            "primary_type" => "bug",
            "secondary_type" => "flying"
        ],
        [
            "id" => 124,
            "name" => "jynx",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png",
            "base_experience" => 159,
            "height" => 14,
            "weight" => 406,
            "attack" => 50,
            "defense" => 35,
            "hp" => 65,
            "speed" => 95,
            "special_attack" => 115,
            "special_defense" => 95,
            "primary_type" => "ice",
            "secondary_type" => "psychic"
        ],
        [
            "id" => 125,
            "name" => "electabuzz",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png",
            "base_experience" => 172,
            "height" => 11,
            "weight" => 300,
            "attack" => 83,
            "defense" => 57,
            "hp" => 65,
            "speed" => 105,
            "special_attack" => 95,
            "special_defense" => 85,
            "primary_type" => "electric",
            "secondary_type" => null
        ],
        [
            "id" => 126,
            "name" => "magmar",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png",
            "base_experience" => 173,
            "height" => 13,
            "weight" => 445,
            "attack" => 95,
            "defense" => 57,
            "hp" => 65,
            "speed" => 93,
            "special_attack" => 100,
            "special_defense" => 85,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 127,
            "name" => "pinsir",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png",
            "base_experience" => 175,
            "height" => 15,
            "weight" => 550,
            "attack" => 125,
            "defense" => 100,
            "hp" => 65,
            "speed" => 85,
            "special_attack" => 55,
            "special_defense" => 70,
            "primary_type" => "bug",
            "secondary_type" => null
        ],
        [
            "id" => 128,
            "name" => "tauros",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png",
            "base_experience" => 172,
            "height" => 14,
            "weight" => 884,
            "attack" => 100,
            "defense" => 95,
            "hp" => 75,
            "speed" => 110,
            "special_attack" => 40,
            "special_defense" => 70,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 129,
            "name" => "magikarp",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png",
            "base_experience" => 40,
            "height" => 9,
            "weight" => 100,
            "attack" => 10,
            "defense" => 55,
            "hp" => 20,
            "speed" => 80,
            "special_attack" => 15,
            "special_defense" => 20,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 130,
            "name" => "gyarados",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
            "base_experience" => 189,
            "height" => 65,
            "weight" => 2350,
            "attack" => 125,
            "defense" => 79,
            "hp" => 95,
            "speed" => 81,
            "special_attack" => 60,
            "special_defense" => 100,
            "primary_type" => "water",
            "secondary_type" => "flying"
        ],
        [
            "id" => 131,
            "name" => "lapras",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
            "base_experience" => 187,
            "height" => 25,
            "weight" => 2200,
            "attack" => 85,
            "defense" => 80,
            "hp" => 130,
            "speed" => 60,
            "special_attack" => 85,
            "special_defense" => 95,
            "primary_type" => "water",
            "secondary_type" => "ice"
        ],
        [
            "id" => 132,
            "name" => "ditto",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png",
            "base_experience" => 101,
            "height" => 3,
            "weight" => 40,
            "attack" => 48,
            "defense" => 48,
            "hp" => 48,
            "speed" => 48,
            "special_attack" => 48,
            "special_defense" => 48,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 133,
            "name" => "eevee",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
            "base_experience" => 65,
            "height" => 3,
            "weight" => 65,
            "attack" => 55,
            "defense" => 50,
            "hp" => 55,
            "speed" => 55,
            "special_attack" => 45,
            "special_defense" => 65,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 134,
            "name" => "vaporeon",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
            "base_experience" => 184,
            "height" => 10,
            "weight" => 290,
            "attack" => 65,
            "defense" => 60,
            "hp" => 130,
            "speed" => 65,
            "special_attack" => 110,
            "special_defense" => 95,
            "primary_type" => "water",
            "secondary_type" => null
        ],
        [
            "id" => 135,
            "name" => "jolteon",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png",
            "base_experience" => 184,
            "height" => 8,
            "weight" => 245,
            "attack" => 65,
            "defense" => 60,
            "hp" => 65,
            "speed" => 130,
            "special_attack" => 110,
            "special_defense" => 95,
            "primary_type" => "electric",
            "secondary_type" => null
        ],
        [
            "id" => 136,
            "name" => "flareon",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png",
            "base_experience" => 184,
            "height" => 9,
            "weight" => 250,
            "attack" => 130,
            "defense" => 60,
            "hp" => 65,
            "speed" => 65,
            "special_attack" => 95,
            "special_defense" => 110,
            "primary_type" => "fire",
            "secondary_type" => null
        ],
        [
            "id" => 137,
            "name" => "porygon",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png",
            "base_experience" => 79,
            "height" => 8,
            "weight" => 365,
            "attack" => 60,
            "defense" => 70,
            "hp" => 65,
            "speed" => 40,
            "special_attack" => 85,
            "special_defense" => 75,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 138,
            "name" => "omanyte",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png",
            "base_experience" => 71,
            "height" => 4,
            "weight" => 75,
            "attack" => 40,
            "defense" => 100,
            "hp" => 35,
            "speed" => 35,
            "special_attack" => 90,
            "special_defense" => 55,
            "primary_type" => "rock",
            "secondary_type" => "water"
        ],
        [
            "id" => 139,
            "name" => "omastar",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png",
            "base_experience" => 173,
            "height" => 10,
            "weight" => 350,
            "attack" => 60,
            "defense" => 125,
            "hp" => 70,
            "speed" => 55,
            "special_attack" => 115,
            "special_defense" => 70,
            "primary_type" => "rock",
            "secondary_type" => "water"
        ],
        [
            "id" => 140,
            "name" => "kabuto",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png",
            "base_experience" => 71,
            "height" => 5,
            "weight" => 115,
            "attack" => 80,
            "defense" => 90,
            "hp" => 30,
            "speed" => 55,
            "special_attack" => 55,
            "special_defense" => 45,
            "primary_type" => "rock",
            "secondary_type" => "water"
        ],
        [
            "id" => 141,
            "name" => "kabutops",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png",
            "base_experience" => 173,
            "height" => 13,
            "weight" => 405,
            "attack" => 115,
            "defense" => 105,
            "hp" => 60,
            "speed" => 80,
            "special_attack" => 65,
            "special_defense" => 70,
            "primary_type" => "rock",
            "secondary_type" => "water"
        ],
        [
            "id" => 142,
            "name" => "aerodactyl",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png",
            "base_experience" => 180,
            "height" => 18,
            "weight" => 590,
            "attack" => 105,
            "defense" => 65,
            "hp" => 80,
            "speed" => 130,
            "special_attack" => 60,
            "special_defense" => 75,
            "primary_type" => "rock",
            "secondary_type" => "flying"
        ],
        [
            "id" => 143,
            "name" => "snorlax",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
            "base_experience" => 189,
            "height" => 21,
            "weight" => 4600,
            "attack" => 110,
            "defense" => 65,
            "hp" => 160,
            "speed" => 30,
            "special_attack" => 65,
            "special_defense" => 110,
            "primary_type" => "normal",
            "secondary_type" => null
        ],
        [
            "id" => 144,
            "name" => "articuno",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
            "base_experience" => 290,
            "height" => 17,
            "weight" => 554,
            "attack" => 85,
            "defense" => 100,
            "hp" => 90,
            "speed" => 85,
            "special_attack" => 95,
            "special_defense" => 125,
            "primary_type" => "ice",
            "secondary_type" => "flying"
        ],
        [
            "id" => 145,
            "name" => "zapdos",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
            "base_experience" => 290,
            "height" => 16,
            "weight" => 526,
            "attack" => 90,
            "defense" => 85,
            "hp" => 90,
            "speed" => 100,
            "special_attack" => 125,
            "special_defense" => 90,
            "primary_type" => "electric",
            "secondary_type" => "flying"
        ],
        [
            "id" => 146,
            "name" => "moltres",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png",
            "base_experience" => 290,
            "height" => 20,
            "weight" => 600,
            "attack" => 100,
            "defense" => 90,
            "hp" => 90,
            "speed" => 90,
            "special_attack" => 125,
            "special_defense" => 85,
            "primary_type" => "fire",
            "secondary_type" => "flying"
        ],
        [
            "id" => 147,
            "name" => "dratini",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
            "base_experience" => 60,
            "height" => 18,
            "weight" => 33,
            "attack" => 64,
            "defense" => 45,
            "hp" => 41,
            "speed" => 50,
            "special_attack" => 50,
            "special_defense" => 50,
            "primary_type" => "dragon",
            "secondary_type" => null
        ],
        [
            "id" => 148,
            "name" => "dragonair",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png",
            "base_experience" => 147,
            "height" => 40,
            "weight" => 165,
            "attack" => 84,
            "defense" => 65,
            "hp" => 61,
            "speed" => 70,
            "special_attack" => 70,
            "special_defense" => 70,
            "primary_type" => "dragon",
            "secondary_type" => null
        ],
        [
            "id" => 149,
            "name" => "dragonite",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
            "base_experience" => 300,
            "height" => 22,
            "weight" => 2100,
            "attack" => 134,
            "defense" => 95,
            "hp" => 91,
            "speed" => 80,
            "special_attack" => 100,
            "special_defense" => 100,
            "primary_type" => "dragon",
            "secondary_type" => "flying"
        ],
        [
            "id" => 150,
            "name" => "mewtwo",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
            "base_experience" => 340,
            "height" => 20,
            "weight" => 1220,
            "attack" => 110,
            "defense" => 90,
            "hp" => 106,
            "speed" => 130,
            "special_attack" => 154,
            "special_defense" => 90,
            "primary_type" => "psychic",
            "secondary_type" => null
        ],
        [
            "id" => 151,
            "name" => "mew",
            "image" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
            "base_experience" => 300,
            "height" => 4,
            "weight" => 40,
            "attack" => 100,
            "defense" => 100,
            "hp" => 100,
            "speed" => 100,
            "special_attack" => 100,
            "special_defense" => 100,
            "primary_type" => "psychic",
            "secondary_type" => null
        ]
    ];
}
